name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  lint:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install flake8 flake8-tabs
    - name: Lint
      run: flake8 addon
